version: '3.6'
services:
  api:
    container_name: api
    restart: always
    env_file:
      - ./.env
    build: .
    ports:
      - '4444:4444'
    depends_on:
      - mongo

  mongo:
    container_name: database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

volumes:
  data-volume:
